name: Testing IoT-Dashboard setup

on: [push]

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Building Docker setup 
        run: |
          cp /github-action/docker-iot-dashboard/env .env
          docker-compose pull
          docker-compose build
      - name: Running IoT-dashboard Container
        run: |
          docker-compose run nginx bash -c "touch /etc/nginx/authdata/influxdb/.htpasswd ; touch /etc/nginx/authdata/nodered/.htpasswd ; chown www-data /etc/nginx/authdata/influxdb/.htpasswd ; chown www-data /etc/nginx/authdata/nodered/.htpasswd ; echo "test101" | htpasswd -c -i /etc/nginx/authdata/nodered/.htpasswd admin ; echo "test101" | htpasswd -c -i /etc/nginx/authdata/nodered/.htpasswd admin"
          docker-compose up -d --build
          sleep 2m
          docker-compose down
          echo "successfully created!"
