name: Testing IoT-Dashboard setup

on: [push]

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: List Files
        run: |
          hostname -f
          pwd
          ls -a
          cp /github-action/docker-iot-dashboard/env .env
          cat .env
          docker-compose pull
          docker-compose build
          docker-compose run nginx /bin/bash
          #touch /etc/nginx/authdata/influxdb/.htpasswd
          #touch /etc/nginx/authdata/nodered/.htpasswd
          #chown www-data /etc/nginx/authdata/influxdb/.htpasswd
          #chown www-data /etc/nginx/authdata/nodered/.htpasswd
          #echo "test101" | htpasswd -c -i /etc/nginx/authdata/nodered/.htpasswd admin
          #echo "test101" | htpasswd -c -i /etc/nginx/authdata/nodered/.htpasswd admin
          #exit
          
          echo "successfully created"
