name: Testing IoT-Dashboard setup

on: [push]

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: List Files
        run: |
          hostname -f
          pwd
          ls -a
          echo "$IOT_DASHBOARD_NGINX_FQDN"
